--SAMPLE QUERIES

--NUMBER OF CONFIRMED CASES IN DELAWARE COUNTY
SELECT COUNT(ConfirmedCases) FROM LOCATIONS 
WHERE CountyName = 'Delaware';

--LIST OF THE COUNTIES AND THEIR NUMBER OF CASES FROM MOST TO LEAST
SELECT DISTINCT CountyName, Population, CrisisGrade, ConfirmedCases FROM LOCATIONS
WHERE ConfirmedCases is NOT NULL
ORDER BY ConfirmedCases DESC;

--LIST OF ALL BUCKS COUNTY PEOPLE AFFECTED OVER THE AGE OF 75
SELECT DISTINCT CaseNumber,Fname,Lname,Age FROM PATIENTS
WHERE CaseNumber IN 
(SELECT DISTINCT CaseN FROM LOCATIONS WHERE CountyName = 'Bucks')
AND Age > 75;

--NUMBER OF PA PATIENTS WITH PREVIOUS HEALTH CONDITIONS WHO RECOVERED
SELECT COUNT(CaseNumber) FROM PATIENTS
WHERE CaseNumber IN (SELECT CaseNum FROM OUTCOMES WHERE Status = 'Recovered')
AND PrevHealthConditions = 'Y';

--LIST OF ALL PATIENTS DIAGNOSED ON APRIL 1, 2020
SELECT DISTINCT CaseNumber, Fname, Lname FROM PATIENTS
WHERE CaseNumber IN (SELECT CaseNum FROM OUTCOMES WHERE BeginDate = '1-Apr-2020');

--PERCENTAGE OF NORTHAMPTON COUNTY INFECTED 
SELECT DISTINCT CountyName, ConfirmedCases, Population, ROUND((ConfirmedCases/Population *100),3) FROM LOCATIONS
WHERE CountyName = 'Northampton';

--NUMBER OF PHILADELPHIA COUNTY PATIENTS WITHOUT A CAREGIVER
SELECT COUNT(CaseNumber) FROM PATIENTS
WHERE CaseNumber IN (SELECT CaseN FROM LOCATIONS WHERE CountyName = 'Philadelphia')
AND CaseNumber IN (SELECT CaseNumb FROM CAREGIVERS WHERE DocLicense# IS NULL);

--LIST OF CAREGIVERS  OF ALL PATIENTS UNDER 20
SELECT CaseNumb, DocFname, DocLname, DocLicense# FROM CAREGIVERS
WHERE CaseNumb IN (SELECT CaseNumber FROM PATIENTS WHERE Age < 20);

--FINDING OLDEST RECOVERED PATIENT IN WAYNE
SELECT CaseNumber, Fname, Lname, Age FROM PATIENTS
WHERE CaseNumber IN (SELECT CaseN FROM LOCATIONS WHERE CountyName = 'Wayne')
ORDER BY Age DESC;

--NUMBER OF PEOPLE IN PA WHO HAVE DIED FROM THE VIRUS
SELECT COUNT(CaseNum) FROM OUTCOMES 
WHERE Status = 'Dead'; 

SELECT COUNT(CaseNumber) FROM PATIENTS WHERE CaseNumber IS NOT NULL;

